# https://github.com/marketplace/actions/first-interaction
name: Welcome New Contributors

on: [pull_request, issues, workflow_dispatch]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
#       env:
#             GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: 'Hello there, thanks for opening your first issue. Welcome to the community!'
        pr-message: 'Hello there, thanks for opening your first Pull Request. Someone will review it soon.'
